course_name = "数字逻辑设计"
course_code = "COMP2051"
notices = """2023 级，这门课作为计算机与电子通信大二上三选一的限选课而改为考察。"""
lecturers = [
  { name = "高翠芸", reviews = [
    { content = """一个非常负责的老师，上课条理清晰，面对疑问也会耐心解答，PPT做得简洁明了，每节课前会提前发到群里，偶尔抽查点到，但是认真听课会对学习这门课程有很大帮助，建议按时上课。""", author = { name = "", link = "", date = "" } },
  ] },
  { name = "张春慨", reviews = [
  ] },
]
textbooks = [
  { title = "逻辑设计基础", book_author = "Charles H. Roth,Jr / Larry L. Kinney / 解晓萌、杨清洪译", publisher = "清华大学出版社", edition = "7版", type = "reference", author = { name = "", link = "", date = "" } },
]
online_resources = []
course = [
  { content = """本门课程授课内容与电类专业的数字电子技术基础内容有很大相似度，作为计科的专业课，本门课程对电路的具体电路实现（即数字电子技术基础中的第三、第七和第八章）不做深入要求，对逻辑设计部分要求较高。
实验部分和数字电子技术实验一样要求使用 vivado 写 verilog 语言并下板验证，但是本门课程实验难度更高，且每年实验内容都在变化，可谓是最创新的一门课程了。""", author = { name = "", link = "", date = "" } },
]
exam = [
  { content = """考试难度中等，高分主要集中在 96，97 分段，较为友好，建议认真写作业，复习重点可以放在PPT上，尤其是各种模型的理解分析，掌握做题方法就可以。
考试成绩出的很慢，需要大海捞人，一个多月才出。""", author = { name = "", link = "", date = "" } },
]
lab = [
  { content = """实验很难（难度因人而异，不过没人觉得简单），因为其对于逻辑和细节要求都很高，耗时普遍较长。分为课上与课下两部分，课上部分尽量按时完成，遇到困难一定要及时请教老师与助教，提高解决问题的效率，老师会把课上部分推迟到下节课检查，还算比较人性（课上检查老师会检查上板结果，读一读代码，讲一下怎么实现的）。
硬件描述语言和高级程序设计语言差别很大，很多时候你逻辑对了，但是不符合硬件实现，上板就会出错，也很难调试。就算调试仿真对了，上板不行还是不行的。一定要按照规范编写，不然会出现很多意想不到的错误。
第一节课关于相关操作要认真对待，熟练好。每次实验前尽量将自己的思路先整理清晰再开始写代码，避免不必要的错误。
课程实验有专门的网站，要求和语言语法知识都有，还是不错的。
建议用 vscode 编写 verilog，用过的都说好，vivado 的编辑器一言难尽。
最后一次实验难度超大，需要大量时间和精力，bug 只能自己解决，可能需要几个晚上的头发吧，但是输出正确结果时还是很高兴的。""", author = { name = "", link = "", date = "" } },
]
advice = []
schedule = []
related_links = [
  { content = "https://github.com/capoo-fan/class-experiment/tree/main/%E6%95%B0%E5%AD%97%E9%80%BB%E8%BE%91%E7%94%B5%E8%B7%AF", author = { name = "", link = "", date = "" } },
]
misc = [
  { content = "不会完全按照课本进行讲授，每年讲授内容也不完全相同，学习请以当年 PPT 为准，教材仅供参考。", author = { name = "", link = "", date = "" } },
]